include: package:very_good_analysis/analysis_options.yaml
analyzer: 

  exclude:
    - lib/app/gen/l10n/intl/messages_all.dart
    - lib/app/gen/l10n/intl/messages_en.dart
    - lib/app/gen/l10n/intl/messages_tr.dart
    - lib/app/gen/l10n/l10n.dart
    - lib/**/*.g.dart
    
linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    sort_pub_dependencies: false