name: base_app_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dart 
  freezed_annotation: ^2.4.1

  # Dependency Injection
  get_it: ^7.6.4
  
  # State Management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3

  # Navigation
  go_router: ^12.1.1

  # JSON
  json_annotation: ^4.8.1

  # Logging
  logging: ^1.2.0
  
dev_dependencies:

  # Flutter Default Dependencies
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
